remote: true

experienceLevel:
 internship: false
 entry: false
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: true
 month: false
 week: false
 24 hours: false

positions:
  - Business Developer
  - Account Manager

locations:
  - Uruguay
  - USA
  - United States of America
  - Germany
  - France

distance: 100

companyBlacklist:


titleBlacklist:
